### ISSUE TITLE
Credentialing: Automatically reject applications if a reference check is pending for >1 month

### ISSUE THREAD

**Issue by lamawmouk** [MIT-LCP/physionet-build#1833] opened 2023-01-25 20:07 UTC
Based on the discussion in the PhysioNet meeting, the current interface of the identity/credentialing submission in the admin console has an Awaiting reference response tab with references who haven't responded for a long time (e.g. response on hold for more > 4 months) .

One suggestion would be to remove users from the system after a certain period of time. @tompollard, is there a reasonable time frame that we could use to remove pending users, maybe have a 2 months threshold.

**Comment by superryeti** [comment] 2023-01-27 17:17
Hi @tompollard , 

And i could think of the following for this issue

1. Do the check for the duration of pending reference  validation just before the content is rendered on the console(on the views.py), and then reject the application. (This sound like a terrible idea as we would be waiting until someone loads the console app and opens the credentialing section)

2. Do some kind of periodic check  with some kind of scheduling tool, as this might help reduce the work load on the server during busy hours(when people are using the console app) compared to option1
Also it kind of makes sense to this check in batch as its not something that is super important to do exactly after like 120 days and 0. Maybe every day at the time when the site has less visitors(like after midnight)[Kind of like how netflix does with subscriptions

**Comment by tompollard** [comment] 2023-01-27 17:29
Thanks @amitupreti my vote would be for option 2! Sound okay to you @bemoody?

**Comment by lamawmouk** [comment] 2023-01-27 19:24
We could possibly apply a method in the form, by creating a CredentialApplication form and then using a clean method in the form to check the response time of the reference after the user has submitted the form.
For example, we can add the clean method in the form which will be called after the user submits the form and before the form's data is saved to the database. If the response time is greater than 2 months, the application will stay or be deleted from the table.  We could use  to set the user attribute of the CredentialApplication object to None, but the itself will still exist in the database or use  CredentialApplication.objects.filter(user=self.user).delete() to remove the CredentialApplication object from the database.

**Comment by superryeti** [comment] 2023-01-27 19:41
@lamawmouk Sorry if i misunderstood the original issue or if i am misunderstanding your latest comment.

From my understanding the issue is, there is a lot of credentialed applications submission, where references have not responded. So we want to reject the application automatically after x months.

But based on your recent comment, we seem to be discussing to check some kind of response time when a user is trying to submit an Application from here http://localhost:8000/credential-application/.

Wouldn't  the checking of response time be done in the future, after the user submits form, the approver approves id and requests reference verification?

**Comment by tompollard** [comment] 2023-01-27 19:44
> From my understanding the issue is, there is a lot of credentialed applications submission, where references have not responded. So we want to reject the application automatically after x months.

This is correct from my understanding too @amitupreti.

**Comment by lamawmouk** [comment] 2023-01-27 22:44
@amitupreti that is correct! Here is codebase of what I was thinking for the method (for the `CredentialApplication` class in the models) if you might need it the workflow:
``` 
def check_response_time(self):
          """ Removes applications that have not been responded to in 2 months """ 
          if self.reference_contact_datetime is not None:
            response_time = (timezone.now() - self.reference_contact_datetime).days
            if response_time > 60:
                self.user = None
 ```

**Comment by superryeti** [comment] 2023-03-02 16:58
resolved by https://github.com/MIT-LCP/physionet-build/pull/1846

**Closed as completed by superryeti** 2023-03-02 16:58 UTC
